icons_format = "{icon}"

[theme]
theme = "dracula"
[theme.overrides]

[icons]
icons = "awesome6"

[[block]]
block = "pomodoro"
notify_cmd = "notify-send '{msg}'"
blocking_cmd = false

[[block]]
block = "focused_window"
[block.format]
full = " $title.str |"
short = " $title.str(max_w:15) |"

[[block]]
block = "net"
format = " $icon {$ssid} "

[[block]]
block = "battery"

[[block]]
block = "rofication"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%d/%m %R') "
